const cropsData = [
  {
    "City":"seattle",
    "LabelID":264820,
    "LabelTypeID":3,
    "CanvasX":369,
    "CanvasY":183,
    "Group":0,
    "Order":0
  },
  {
    "City":"seattle",
    "LabelID":191782,
    "LabelTypeID":3,
    "CanvasX":330,
    "CanvasY":310,
    "Group":0,
    "Order":1
  },
  {
    "City":"chicago",
    "LabelID":46864,
    "LabelTypeID":3,
    "CanvasX":374,
    "CanvasY":289,
    "Group":0,
    "Order":2
  },
  {
    "City":"chicago",
    "LabelID":15148,
    "LabelTypeID":3,
    "CanvasX":328,
    "CanvasY":300,
    "Group":0,
    "Order":3
  },
  {
    "City":"lapiedad",
    "LabelID":997,
    "LabelTypeID":3,
    "CanvasX":301,
    "CanvasY":229,
    "Group":0,
    "Order":4
  },
  {
    "City":"oradell",
    "LabelID":12344,
    "LabelTypeID":3,
    "CanvasX":308,
    "CanvasY":270,
    "Group":0,
    "Order":5
  },
  {
    "City":"seattle",
    "LabelID":191179,
    "LabelTypeID":3,
    "CanvasX":213,
    "CanvasY":230,
    "Group":1,
    "Order":0
  },
  {
    "City":"st_louis",
    "LabelID":3850,
    "LabelTypeID":3,
    "CanvasX":380,
    "CanvasY":240,
    "Group":1,
    "Order":1
  },
  {
    "City":"oradell",
    "LabelID":4765,
    "LabelTypeID":3,
    "CanvasX":377,
    "CanvasY":178,
    "Group":1,
    "Order":2
  },
  {
    "City":"st_louis",
    "LabelID":7558,
    "LabelTypeID":3,
    "CanvasX":344,
    "CanvasY":188,
    "Group":1,
    "Order":3
  },
  {
    "City":"columbus",
    "LabelID":12830,
    "LabelTypeID":3,
    "CanvasX":390,
    "CanvasY":163,
    "Group":1,
    "Order":4
  },
  {
    "City":"seattle",
    "LabelID":229205,
    "LabelTypeID":3,
    "CanvasX":245,
    "CanvasY":296,
    "Group":1,
    "Order":5
  },
  {
    "City":"seattle",
    "LabelID":100492,
    "LabelTypeID":3,
    "CanvasX":193,
    "CanvasY":190,
    "Group":2,
    "Order":0
  },
  {
    "City":"columbus",
    "LabelID":36038,
    "LabelTypeID":3,
    "CanvasX":265,
    "CanvasY":230,
    "Group":2,
    "Order":1
  },
  {
    "City":"seattle",
    "LabelID":197213,
    "LabelTypeID":3,
    "CanvasX":370,
    "CanvasY":135,
    "Group":2,
    "Order":2
  },
  {
    "City":"teaneck",
    "LabelID":3430,
    "LabelTypeID":3,
    "CanvasX":290,
    "CanvasY":300,
    "Group":2,
    "Order":3
  },
  {
    "City":"seattle",
    "LabelID":139731,
    "LabelTypeID":3,
    "CanvasX":318,
    "CanvasY":203,
    "Group":2,
    "Order":4
  },
  {
    "City":"seattle",
    "LabelID":208754,
    "LabelTypeID":3,
    "CanvasX":385,
    "CanvasY":300,
    "Group":2,
    "Order":5
  },
  {
    "City":"oradell",
    "LabelID":11350,
    "LabelTypeID":4,
    "CanvasX":175,
    "CanvasY":370,
    "Group":3,
    "Order":0
  },
  {
    "City":"oradell",
    "LabelID":11707,
    "LabelTypeID":4,
    "CanvasX":440,
    "CanvasY":230,
    "Group":3,
    "Order":1
  },
  {
    "City":"seattle",
    "LabelID":209069,
    "LabelTypeID":4,
    "CanvasX":390,
    "CanvasY":225,
    "Group":3,
    "Order":2
  },
  {
    "City":"oradell",
    "LabelID":562,
    "LabelTypeID":4,
    "CanvasX":368,
    "CanvasY":269,
    "Group":3,
    "Order":3
  },
  {
    "City":"st_louis",
    "LabelID":2022,
    "LabelTypeID":4,
    "CanvasX":320,
    "CanvasY":140,
    "Group":3,
    "Order":4
  },
  {
    "City":"st_louis",
    "LabelID":5941,
    "LabelTypeID":4,
    "CanvasX":382,
    "CanvasY":200,
    "Group":3,
    "Order":5
  },
  {
    "City":"chicago",
    "LabelID":39245,
    "LabelTypeID":4,
    "CanvasX":350,
    "CanvasY":330,
    "Group":4,
    "Order":0
  },
  {
    "City":"columbus",
    "LabelID":39006,
    "LabelTypeID":4,
    "CanvasX":350,
    "CanvasY":240,
    "Group":4,
    "Order":1
  },
  {
    "City":"st_louis",
    "LabelID":2080,
    "LabelTypeID":4,
    "CanvasX":350,
    "CanvasY":270,
    "Group":4,
    "Order":2
  },
  {
    "City":"columbus",
    "LabelID":30419,
    "LabelTypeID":4,
    "CanvasX":350,
    "CanvasY":340,
    "Group":4,
    "Order":3
  },
  {
    "City":"st_louis",
    "LabelID":262,
    "LabelTypeID":4,
    "CanvasX":258,
    "CanvasY":181,
    "Group":4,
    "Order":4
  },
  {
    "City":"amsterdam",
    "LabelID":26619,
    "LabelTypeID":4,
    "CanvasX":312,
    "CanvasY":229,
    "Group":4,
    "Order":5
  },
  {
    "City":"chicago",
    "LabelID":24214,
    "LabelTypeID":4,
    "CanvasX":322,
    "CanvasY":293,
    "Group":5,
    "Order":0
  },
  {
    "City":"seattle",
    "LabelID":273517,
    "LabelTypeID":4,
    "CanvasX":350,
    "CanvasY":330,
    "Group":5,
    "Order":1
  },
  {
    "City":"oradell",
    "LabelID":456,
    "LabelTypeID":4,
    "CanvasX":393,
    "CanvasY":195,
    "Group":5,
    "Order":2
  },
  {
    "City":"chicago",
    "LabelID":631,
    "LabelTypeID":4,
    "CanvasX":370,
    "CanvasY":244,
    "Group":5,
    "Order":3
  },
  {
    "City":"st_louis",
    "LabelID":3172,
    "LabelTypeID":4,
    "CanvasX":548,
    "CanvasY":275,
    "Group":5,
    "Order":4
  },
  {
    "City":"st_louis",
    "LabelID":2697,
    "LabelTypeID":4,
    "CanvasX":350,
    "CanvasY":270,
    "Group":5,
    "Order":5
  },
  {
    "City":"oradell",
    "LabelID":669,
    "LabelTypeID":3,
    "CanvasX":320,
    "CanvasY":190,
    "Group":6,
    "Order":0
  },
  {
    "City":"st_louis",
    "LabelID":1777,
    "LabelTypeID":3,
    "CanvasX":305,
    "CanvasY":132,
    "Group":6,
    "Order":1
  },
  {
    "City":"st_louis",
    "LabelID":7061,
    "LabelTypeID":3,
    "CanvasX":327,
    "CanvasY":166,
    "Group":6,
    "Order":2
  },
  {
    "City":"oradell",
    "LabelID":5518,
    "LabelTypeID":4,
    "CanvasX":320,
    "CanvasY":240,
    "Group":6,
    "Order":3
  },
  {
    "City":"seattle",
    "LabelID":258182,
    "LabelTypeID":1,
    "CanvasX":360,
    "CanvasY":310,
    "Group":7,
    "Order":0
  },
  {
    "City":"chicago",
    "LabelID":3047,
    "LabelTypeID":1,
    "CanvasX":388,
    "CanvasY":286,
    "Group":7,
    "Order":1
  },
  {
    "City":"seattle",
    "LabelID":16482,
    "LabelTypeID":1,
    "CanvasX":340,
    "CanvasY":250,
    "Group":7,
    "Order":2
  },
  {
    "City":"la_piedad",
    "LabelID":2377,
    "LabelTypeID":1,
    "CanvasX":443,
    "CanvasY":304,
    "Group":7,
    "Order":3
  },
  {
    "City":"cdmx",
    "LabelID":44798,
    "LabelTypeID":1,
    "CanvasX":358,
    "CanvasY":253,
    "Group":7,
    "Order":4
  },
  {
    "City":"cdmx",
    "LabelID":46135,
    "LabelTypeID":1,
    "CanvasX":325,
    "CanvasY":214,
    "Group":7,
    "Order":5
  },
  {
    "City":"seattle",
    "LabelID":74650,
    "LabelTypeID":2,
    "CanvasX":154,
    "CanvasY":220,
    "Group":8,
    "Order":0
  },
  {
    "City":"seattle",
    "LabelID":145241,
    "LabelTypeID":2,
    "CanvasX":290,
    "CanvasY":350,
    "Group":8,
    "Order":1
  },
  {
    "City":"seattle",
    "LabelID":156512,
    "LabelTypeID":2,
    "CanvasX":240,
    "CanvasY":386,
    "Group":8,
    "Order":2
  },
  {
    "City":"seattle",
    "LabelID":168483,
    "LabelTypeID":2,
    "CanvasX":250,
    "CanvasY":290,
    "Group":8,
    "Order":3
  },
  {
    "City":"seattle",
    "LabelID":175408,
    "LabelTypeID":2,
    "CanvasX":175,
    "CanvasY":350,
    "Group":8,
    "Order":4
  },
  {
    "City":"seattle",
    "LabelID":176648,
    "LabelTypeID":2,
    "CanvasX":390,
    "CanvasY":350,
    "Group":8,
    "Order":5
  }
];

export default cropsData;